image: python:3.6

# TODO: Create a simple alias for irods once GitLab implements this
# https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#accessing-the-services
# https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1466
services:
  - redis:latest
  - mjstealey/irods-provider-postgres:latest

variables:
  IRODS_ZONE_NAME: omicsZone
  TASKFLOW_REDIS_URL: http://redis:6379
  TASKFLOW_IRODS_TEST_HOST: mjstealey-irods-provider-postgres
  TASKFLOW_IRODS_TEST_PORT: 1247
  OMICS_TASKFLOW_SETTINGS: ./config/production.py

before_script:
  - pip3 install virtualenv
  - virtualenv env
  - source env/bin/activate
  - pip3 install -r ./requirements.txt

all_tests:
  script:
    - ./utility/test.sh
    - ./utility/black.sh --check
  when: on_success
